development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: test_user@someEmail.com
  :password: test_pswd
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: test_user@someEmail.com
  :password: test_pswd
  :enable_starttls_auto: true